### ISSUE TITLE
Ненужный код

### ISSUE THREAD

**Issue by Biryukov239** [VanyaXIII/matrix-multiplication#1]
Пожалуйста, перепишите [это](https://github.com/VanyaXIII/matrix-multiplication/blob/main/src/main/java/org/example/multiplication/Kernels.java) с использованием цикла и массива длины 8. Это неприятно читать. И если Вы скажите, что так производительнее, то я попрошу сначала предъявить бенчмарки. Потому что я их сделал и через `FloatArray` получается реально быстрее, чем 8 переменных.

**Comment by VanyaXIII** [comment]
Здравствуйте, Григорий! Во-первых, в Java нет FloatArray, Вы, вероятно, путаете с Kotlin'ом; во-вторых, ознакомьтесь, пожалуйста, с докуменатацией используемой в проекте библиотеки [aparapi](https://aparapi.com/documentation/kernel-guidelines.html). К сожалению, внутри метода kernel.run нельзя создавать массивы(как и использовать new и все, что использует new "под капотом")
